// Card data — Gauntlet AI Cohort 6, Pokémon TCG Pocket rules.
// Types: fire=Frontend, water=Data, grass=ML, electric=Infra, psychic=Agents, fighting=Evals. WEAK map in battle.js (+20).
// `name` is the card's Pokémon-style name; `real` is the person. Every card has 2 moves: its type's COMMON move (shared) + a signature move `sig`.
// Move cost: { t: n, c: m } = n energy of the card's own type + m of any type. flip: tails does nothing. self: recoil.
// ex cards are worth 2 points when knocked out. retreat = energy discarded to retreat (default 1).
window.TYPES = {
  fire: { label: "Frontend", icon: "🔥" }, water: { label: "Data", icon: "💧" }, grass: { label: "ML", icon: "🌿" },
  electric: { label: "Infra", icon: "⚡" }, psychic: { label: "Agents", icon: "🔮" }, fighting: { label: "Evals", icon: "🥊" },
};
window.COMMON = {
  fire: { name: "Hot Reload", cost: { t: 1 }, dmg: 20 },
  water: { name: "dbt Run", cost: { t: 1 }, dmg: 20 },
  grass: { name: "Fine-tune", cost: { t: 1 }, dmg: 20 },
  electric: { name: "kubectl apply", cost: { t: 1 }, dmg: 20 },
  psychic: { name: "Tool Call", cost: { t: 1 }, dmg: 20 },
  fighting: { name: "Rubric Check", cost: { t: 1 }, dmg: 20 },
};
// Order matches the portal's Guess Who board (left→right, top→bottom), then the three not on the board.
window.CARDS = [
  { id: "emily-liang", name: "Swiftmily", real: "Emily Liang", photo: "photos/emily-liang.jpg", type: "fire", hp: 90,
    sig: { name: "App Store Review", cost: { t: 2 }, dmg: 70, flip: true, text: "Rejected. Resubmit." },
    flavor: "Ships iOS at Realtor.com. Has opinions about your storyboard." },
  { id: "matt-duque", name: "Duquetron", real: "Matt Duque", photo: "photos/matt-duque.jpg", type: "electric", hp: 110, retreat: 2,
    sig: { name: "HVAC Overclock", cost: { t: 2 }, dmg: 60 },
    flavor: "Ten years at Daikin. Keeps the servers and the room cool." },
  { id: "adam-roch", name: "Rochmander", real: "Adam Roch", photo: "photos/adam-roch.jpg", type: "electric", hp: 100,
    sig: { name: "Oracle Query", cost: { t: 1, c: 1 }, dmg: 50, text: "Has seen prod at 3am." },
    flavor: "Bank prod support. Nothing you deploy will surprise him." },
  { id: "jordan-phillips", name: "Jordeon", real: "Jordan Phillips", photo: "photos/jordan-phillips.jpg", type: "psychic", hp: 90,
    sig: { name: "Telehealth Launch", cost: { t: 2 }, dmg: 70, flip: true, text: "Shipped during COVID." },
    flavor: "Bootstrapped athenahealth's Telehealth. Speaks fluent MCP." },
  { id: "kevin-reynolds", name: "Kevalu", real: "Kevin Reynolds", photo: "photos/kevin-reynolds.jpg", type: "fighting", hp: 90,
    sig: { name: "Grade the Agent", cost: { t: 2 }, dmg: 70, flip: true, text: "Your PR: 3/10." },
    flavor: "Evaluates AI coding agents for a living. Yes, including this one." },
  { id: "matt-mccaleb", name: "Calebra", real: "Matt McCaleb", photo: "photos/matt-mccaleb.jpg", type: "water", hp: 100,
    sig: { name: "Acquisition", cost: { t: 2 }, dmg: 70, flip: true, text: "Now owned by UTA." },
    flavor: "Ran a data team straight through an acquisition." },
  { id: "kelly-he", name: "Kellix", real: "Kelly He", photo: "photos/kelly-he.jpg", type: "fire", hp: 90,
    sig: { name: "Fortune 100 Launch", cost: { t: 2 }, dmg: 60 },
    flavor: "E-commerce for tens of millions of users. Then an iOS app, for fun." },
  { id: "will-parks", name: "Willsaur", real: "Will Parks", photo: "photos/will-parks.jpg", type: "fire", hp: 100,
    sig: { name: "HIPAA Compliance", cost: { t: 1, c: 1 }, dmg: 50, text: "Damage is redacted." },
    flavor: "Medical hardware apps. His code is why the device works." },
  { id: "tigran-asriyan", name: "Tigrash", real: "Tigran Asriyan", photo: "photos/tigran-asriyan.jpg", type: "fire", hp: 80, retreat: 0,
    sig: { name: "IPFS Migration", cost: { t: 2, c: 1 }, dmg: 80, flip: true, text: "8s → under 1s." },
    flavor: "20k monthly users on a Solana payments app. Fast is a personality." },
  { id: "david-dean", name: "Deanzard", real: "David Dean", photo: "photos/david-dean.jpg", type: "fire", hp: 90,
    sig: { name: "Enterprise Standards", cost: { t: 1, c: 1 }, dmg: 50 },
    flavor: "Ex-AmEx UI lead. Now teaches justice-involved students to ship." },
  { id: "shamilah-faria", name: "Shamilax", real: "Shamilah Faria", photo: "photos/shamilah-faria.jpg", type: "electric", hp: 90,
    sig: { name: "Ship at 3:47 AM", cost: { t: 2, c: 1 }, dmg: 90, flip: true, self: 20, text: "Also hits yourself for 20." },
    flavor: "Event-driven architecture. Event-driven sleep schedule. Built this game." },
  { id: "rodolfo-rodriguez", name: "Rodolform", real: "Rodolfo Rodriguez", photo: "photos/rodolfo-rodriguez.jpg", type: "electric", hp: 100,
    sig: { name: "Cut Cloud Costs 100x", cost: { t: 2 }, dmg: 60, text: "Literally one click." },
    flavor: "Saved Broadcom 100 hours a month with one click." },
  { id: "cam-moore", name: "Camtron", real: "Cam Moore", photo: "photos/cam-moore.jpg", type: "water", hp: 100,
    sig: { name: "Snowflake Bill", cost: { t: 2 }, dmg: 70, flip: true, text: "Ouch." },
    flavor: "Founding data team at Replicated. Knows exactly what the dashboard costs." },
  { id: "john-martin", name: "Martinix", real: "John Martin", photo: "photos/john-martin.jpg", type: "psychic", hp: 100,
    sig: { name: "2,200 Boundary Tests", cost: { t: 2 }, dmg: 60, text: "Never misses." },
    flavor: "Clinical co-pilot in OpenEMR. Deny-by-default, including to you." },
  { id: "josie-machalek", name: "Josieon", real: "Josie Machalek", photo: "photos/josie-machalek.jpg", type: "grass", hp: 100,
    sig: { name: "Reasoning Pipeline", cost: { t: 2 }, dmg: 70, flip: true },
    flavor: "Deloitte AI lead. Saved $700K/yr as an intern. An intern." },
  { id: "gabe-trinidad", name: "Trinidactyl", real: "Gabe Trinidad", photo: "photos/gabe-trinidad.jpg", type: "fire", hp: 90,
    sig: { name: "GraphQL Migration", cost: { t: 2 }, dmg: 60, text: "Load time 3s → 1s." },
    flavor: "Cut query load 75% at Apploi. Your components are not consistent enough." },
  { id: "sohail-siddiqui", name: "Sohailstorm", real: "Sohail Siddiqui", photo: "photos/sohail-siddiqui.jpg", type: "grass", hp: 130, ex: true, retreat: 2,
    sig: { name: "RAG Eval", cost: { t: 2, c: 1 }, dmg: 90, flip: true },
    flavor: "Builds RAG for the FDA inside GovCloud. No, you can't curl it." },
  { id: "alex-miller", name: "Alexecutor", real: "Alex Miller", photo: "photos/alex-miller.jpg", type: "psychic", hp: 100,
    sig: { name: "DevSecOps Audit", cost: { t: 2 }, dmg: 70, flip: true, text: "Held a Secret clearance." },
    flavor: "Lead engineer at ACT Labs: agent marketplaces, MCP discovery, a robotics platform on the side." },
  { id: "hank-holcomb", name: "Hankasaur", real: "Hank Holcomb", photo: "photos/hank-holcomb.jpg", type: "fire", hp: 140, ex: true, retreat: 2,
    sig: { name: "Nine-Year Tenure", cost: { t: 3 }, dmg: 100 },
    flavor: "CTO of Cheers since 2017. First hire. $100M+ brand. Still here." },
  { id: "aaryan-das", name: "Aaryanite", real: "Aaryan Das", photo: "photos/aaryan-das.jpg", type: "electric", hp: 90,
    sig: { name: "Payment Processing", cost: { t: 1, c: 1 }, dmg: 50 },
    flavor: "Payments at Bank of America. The phone menu was him. Sorry." },
  { id: "lauren-porr", name: "Porrbit", real: "Lauren Porr", photo: "photos/lauren-porr.jpg", type: "fighting", hp: 100,
    sig: { name: "Red Team Console", cost: { t: 2 }, dmg: 70, flip: true, text: "Deployed on Railway." },
    flavor: "Deputy chief systems engineer on a GPS augmentation system. Yes, satellites." },
  { id: "ruben-lopez", name: "Rubenquake", real: "Ruben Lopez", photo: "photos/ruben-lopez.jpg", type: "water", hp: 100,
    sig: { name: "Wafer Signature", cost: { t: 1, c: 1 }, dmg: 50 },
    flavor: "Semiconductor yield at Samsung. Seismic data on four continents." },
  { id: "adam-nash", name: "Nashwing", real: "Adam Nash", photo: "photos/adam-nash.jpg", type: "psychic", hp: 90,
    sig: { name: "Local LLM Harness", cost: { t: 2 }, dmg: 70, flip: true, text: "No commercial assistants." },
    flavor: "Built his own coding harness around a local model. Also a licensed pilot." },
  { id: "ryan-highfill", name: "Ryanigma", real: "Ryan Highfill", photo: "photos/ryan-highfill.jpg", type: "water", hp: 90,
    sig: { name: "Off the Record", cost: { t: 2 }, dmg: 70, flip: true },
    flavor: "No LinkedIn. No footprint. Maximum mystery." },
  { id: "cristina-guzman", name: "Guzmaestro", real: "Cristina Guzman", photo: "photos/cristina-guzman.jpg", type: "psychic", hp: 130, ex: true, retreat: 2,
    sig: { name: "Adversarial Red Team", cost: { t: 2, c: 1 }, dmg: 90, flip: true },
    flavor: "CTO at Sendengo. Weekly build writeups. Reads your logs for fun." },
  { id: "koby-adu-bonnah", name: "Kobyte", real: "Koby Adu-Bonnah", photo: "photos/koby-adu-bonnah.jpg", type: "electric", hp: 130, ex: true, retreat: 2,
    sig: { name: "1.5 PB Processed", cost: { t: 2, c: 1 }, dmg: 90, self: 10, text: "Hits the disk too." },
    flavor: "Scaled a sender to half of Klaviyo's billion monthly emails. Half." },
  // Not on the portal board — photos from LinkedIn.
  { id: "josh-rochon", name: "Rochonix", real: "Josh Rochon", photo: "photos/josh-rochon.jpg", type: "fire", hp: 90,
    sig: { name: "17-Node LangGraph", cost: { t: 2 }, dmg: 70, flip: true, text: "Only 2 nodes touch an LLM." },
    flavor: "Starbucks, Microsoft, BECU. Figma to React, GraphQL via Apollo." },
  { id: "james-merithew", name: "Merithue", real: "James Merithew", photo: "photos/james-merithew.jpg", type: "water", hp: 100,
    sig: { name: "Executive Dashboard", cost: { t: 2 }, dmg: 60 },
    flavor: "Data viz at LG Ad Solutions. Pets named Alfredo and Truffle." },
  { id: "troy-satchell", name: "Troyager", real: "Troy Satchell", photo: "photos/troy-satchell.jpg", type: "fire", hp: 90,
    sig: { name: "Icon Subset", cost: { t: 1, c: 1 }, dmg: 50, text: "90% smaller payload." },
    flavor: "Solo founder of Clavira. Shrank a design system's icon fonts by 90% and shipped it to 7 teams." },
];
// Trainer cards. Items: any number per turn. Supporters: one per turn. Staff supporters can be added here with a `photo`.
window.TRAINERS = [
  { id: "coffee", kind: "item", name: "Coffee", text: "Heal 20 damage from your active card." },
  { id: "slack-ping", kind: "item", name: "Slack Ping", text: "Put a random person from your deck into your hand." },
  { id: "hotfix", kind: "item", name: "Hotfix", text: "This turn, your active card's retreat cost is 1 less." },
  { id: "weekly-writeup", kind: "supporter", name: "Weekly Writeup", text: "Draw 2 cards." },
  { id: "demo-day", kind: "supporter", name: "Demo Day", text: "This turn, your attacks do +10 damage." },
  { id: "hiring-partner-intro", kind: "supporter", name: "Hiring Partner Intro", text: "Your opponent switches their active card with a benched one." },
  { id: "office-hours", kind: "supporter", name: "Office Hours", text: "Heal 50 damage from your active card." },
  { id: "stipend", kind: "supporter", name: "Stipend", text: "Attach 1 extra energy of your type to your active card." },
];
