// Card data — Gauntlet AI Cohort 6. Types: fire=Frontend, water=Data, grass=ML, electric=Infra, psychic=Agents, fighting=Evals.
// Weakness is per type, not per card: see WEAK in battle.js.
// photo is optional; if missing or fails to load, the card shows a colored circle with initials.
// Optional attack fields: `self` = recoil damage to the attacker; `flip: true` = coin flip, tails does nothing (50%).
// Order matches the portal's Guess Who board (left→right, top→bottom).
window.CARDS = [
  { id: "emily-liang", name: "Emily Liang", photo: "photos/emily-liang.jpg", type: "fire", hp: 90,
    attacks: [{ name: "Swift Rewrite", dmg: 30 }, { name: "App Store Review", dmg: 70, flip: true, text: "Rejected. Resubmit." }],
    flavor: "Ships iOS at Realtor.com. Has opinions about your storyboard." },
  { id: "matt-duque", name: "Matt Duque", photo: "photos/matt-duque.jpg", type: "electric", hp: 110,
    attacks: [{ name: "Industrial Strength", dmg: 30 }, { name: "HVAC Overclock", dmg: 60 }],
    flavor: "Ten years at Daikin. Keeps the servers and the room cool." },
  { id: "adam-roch", name: "Adam Roch", photo: "photos/adam-roch.jpg", type: "electric", hp: 100,
    attacks: [{ name: "Production Support", dmg: 30, text: "Has seen prod at 3am." }, { name: "Oracle Query", dmg: 60 }],
    flavor: "Bank prod support. Nothing you deploy will surprise him." },
  { id: "jordan-phillips", name: "Jordan Phillips", photo: "photos/jordan-phillips.jpg", type: "psychic", hp: 90,
    attacks: [{ name: "Tool Call", dmg: 30 }, { name: "Telehealth Launch", dmg: 70, flip: true, text: "Shipped during COVID." }],
    flavor: "Bootstrapped athenahealth's Telehealth. Speaks fluent MCP." },
  { id: "kevin-reynolds", name: "Kevin Reynolds", photo: "photos/kevin-reynolds.jpg", type: "fighting", hp: 90,
    attacks: [{ name: "Rubric Check", dmg: 30 }, { name: "Grade the Agent", dmg: 70, flip: true, text: "Your PR: 3/10." }],
    flavor: "Evaluates AI coding agents for a living. Yes, including this one." },
  { id: "matt-mccaleb", name: "Matt McCaleb", photo: "photos/matt-mccaleb.jpg", type: "water", hp: 100,
    attacks: [{ name: "Schema Migration", dmg: 30 }, { name: "Acquisition", dmg: 70, flip: true, text: "Now owned by UTA." }],
    flavor: "Ran a data team straight through an acquisition." },
  { id: "kelly-he", name: "Kelly He", photo: "photos/kelly-he.jpg", type: "fire", hp: 90,
    attacks: [{ name: "API Contract", dmg: 30 }, { name: "Fortune 100 Launch", dmg: 70, flip: true }],
    flavor: "E-commerce for tens of millions of users. Then an iOS app, for fun." },
  { id: "will-parks", name: "Will Parks", photo: "photos/will-parks.jpg", type: "fire", hp: 100,
    attacks: [{ name: "Hot Reload", dmg: 30 }, { name: "HIPAA Compliance", dmg: 60, text: "Damage is redacted." }],
    flavor: "Medical hardware apps. His code is why the device works." },
  { id: "tigran-asriyan", name: "Tigran Asriyan", photo: "photos/tigran-asriyan.jpg", type: "fire", hp: 80,
    attacks: [{ name: "Solana Swap", dmg: 30 }, { name: "IPFS Migration", dmg: 80, flip: true, text: "8s → under 1s." }],
    flavor: "20k monthly users on a Solana payments app. Fast is a personality." },
  { id: "david-dean", name: "David Dean", photo: "photos/david-dean.jpg", type: "fire", hp: 90,
    attacks: [{ name: "Code Review", dmg: 30 }, { name: "Enterprise Standards", dmg: 60 }],
    flavor: "Ex-AmEx UI lead. Now teaches justice-involved students to ship." },
  { id: "shamilah-faria", name: "Shamilah Faria", photo: "photos/shamilah-faria.jpg", type: "electric", hp: 90,
    attacks: [{ name: "Kafka Replay", dmg: 30 }, { name: "Ship at 3:47 AM", dmg: 80, flip: true, self: 20, text: "Also hits yourself for 20." }],
    flavor: "Event-driven architecture. Event-driven sleep schedule. Built this game." },
  { id: "rodolfo-rodriguez", name: "Rodolfo Rodriguez", photo: "photos/rodolfo-rodriguez.jpg", type: "electric", hp: 100,
    attacks: [{ name: "Terraform Apply", dmg: 30 }, { name: "Cut Cloud Costs 100x", dmg: 70, flip: true }],
    flavor: "Saved Broadcom 100 hours a month with one click. Literally one click." },
  { id: "cam-moore", name: "Cam Moore", photo: "photos/cam-moore.jpg", type: "water", hp: 100,
    attacks: [{ name: "dbt Run", dmg: 30 }, { name: "Snowflake Bill", dmg: 70, flip: true, text: "Ouch." }],
    flavor: "Founding data team at Replicated. Knows exactly what the dashboard costs." },
  { id: "john-martin", name: "John Martin", photo: "photos/john-martin.jpg", type: "psychic", hp: 100,
    attacks: [{ name: "Deny By Default", dmg: 30 }, { name: "2,200 Boundary Tests", dmg: 70, flip: true }],
    flavor: "Clinical co-pilot in OpenEMR. Deny-by-default, including to you." },
  { id: "josie-machalek", name: "Josie Machalek", photo: "photos/josie-machalek.jpg", type: "grass", hp: 100,
    attacks: [{ name: "PyTorch Warmup", dmg: 30 }, { name: "Reasoning Pipeline", dmg: 70, flip: true }],
    flavor: "Deloitte AI lead. Saved $700K/yr as an intern. An intern." },
  { id: "gabe-trinidad", name: "Gabe Trinidad", photo: "photos/gabe-trinidad.jpg", type: "fire", hp: 90,
    attacks: [{ name: "Design System", dmg: 30 }, { name: "GraphQL Migration", dmg: 70, flip: true, text: "Load time 3s → 1s." }],
    flavor: "Cut query load 75% at Apploi. Your components are not consistent enough." },
  { id: "sohail-siddiqui", name: "Sohail Siddiqui", photo: "photos/sohail-siddiqui.jpg", type: "grass", hp: 110,
    attacks: [{ name: "Air-Gapped Deploy", dmg: 30 }, { name: "RAG Eval", dmg: 70, flip: true }],
    flavor: "Builds RAG for the FDA inside GovCloud. No, you can't curl it." },
  { id: "alex-miller", name: "Alex Miller", photo: "photos/alex-miller.jpg", type: "psychic", hp: 100,
    attacks: [{ name: "Forward Deploy", dmg: 30 }, { name: "DevSecOps Audit", dmg: 70, flip: true, text: "Held a Secret clearance." }],
    flavor: "Lead engineer at ACT Labs: agent marketplaces, MCP discovery, a robotics platform on the side." },
  { id: "hank-holcomb", name: "Hank Holcomb", photo: "photos/hank-holcomb.jpg", type: "fire", hp: 120,
    attacks: [{ name: "First Hire", dmg: 30 }, { name: "Nine-Year Tenure", dmg: 70, flip: true }],
    flavor: "CTO of Cheers since 2017. First hire. $100M+ brand. Still here." },
  { id: "aaryan-das", name: "Aaryan Das", photo: "photos/aaryan-das.jpg", type: "electric", hp: 90,
    attacks: [{ name: "IVR Prompt", dmg: 30 }, { name: "Payment Processing", dmg: 60 }],
    flavor: "Payments at Bank of America. The phone menu was him. Sorry." },
  { id: "lauren-porr", name: "Lauren Porr", photo: "photos/lauren-porr.jpg", type: "fighting", hp: 100,
    attacks: [{ name: "Requirements Review", dmg: 30 }, { name: "Red Team Console", dmg: 70, flip: true, text: "Deployed on Railway." }],
    flavor: "Deputy chief systems engineer on a GPS augmentation system. Yes, satellites." },
  { id: "ruben-lopez", name: "Ruben Lopez", photo: "photos/ruben-lopez.jpg", type: "water", hp: 100,
    attacks: [{ name: "Yield Analysis", dmg: 30 }, { name: "Wafer Signature", dmg: 60 }],
    flavor: "Semiconductor yield at Samsung. Seismic data on four continents." },
  { id: "adam-nash", name: "Adam Nash", photo: "photos/adam-nash.jpg", type: "psychic", hp: 90,
    attacks: [{ name: "Custom MCP Server", dmg: 30 }, { name: "Local LLM Harness", dmg: 70, flip: true, text: "No commercial assistants." }],
    flavor: "Built his own coding harness around a local model. Also a licensed pilot." },
  { id: "ryan-highfill", name: "Ryan Highfill", photo: "photos/ryan-highfill.jpg", type: "water", hp: 90,
    attacks: [{ name: "Stealth Mode", dmg: 30 }, { name: "Off the Record", dmg: 70, flip: true }],
    flavor: "No LinkedIn. No footprint. Maximum mystery." },
  { id: "cristina-guzman", name: "Cristina Guzman", photo: "photos/cristina-guzman.jpg", type: "psychic", hp: 110,
    attacks: [{ name: "CTO Override", dmg: 30 }, { name: "Adversarial Red Team", dmg: 70, flip: true }],
    flavor: "CTO at Sendengo. Weekly build writeups. Reads your logs for fun." },
  { id: "koby-adu-bonnah", name: "Koby Adu-Bonnah", photo: "photos/koby-adu-bonnah.jpg", type: "electric", hp: 110,
    attacks: [{ name: "150 MB/s Ingest", dmg: 30 }, { name: "1.5 PB Processed", dmg: 80, flip: true, self: 10, text: "Hits the disk too." }],
    flavor: "Scaled a sender to half of Klaviyo's billion monthly emails. Half." },
  // Not on the portal board — photos from LinkedIn.
  { id: "josh-rochon", name: "Josh Rochon", photo: "photos/josh-rochon.jpg", type: "fire", hp: 90,
    attacks: [{ name: "Figma to React", dmg: 30 }, { name: "17-Node LangGraph", dmg: 70, flip: true, text: "Only 2 nodes touch an LLM." }],
    flavor: "Starbucks, Microsoft, BECU. Posts a write-up every single week." },
  { id: "james-merithew", name: "James Merithew", photo: "photos/james-merithew.jpg", type: "water", hp: 100,
    attacks: [{ name: "Causal Inference", dmg: 30 }, { name: "Executive Dashboard", dmg: 70, flip: true }],
    flavor: "Data viz at LG Ad Solutions. Pets named Alfredo and Truffle." },
  { id: "tony", name: "Tony", type: "psychic", hp: 99,
    attacks: [{ name: "Glitch", dmg: 30 }, { name: "Rare Candy x99", dmg: 70, flip: true }],
    flavor: "MissingNo. LinkedIn not found, card data corrupted. Do not surf past Cinnabar Island." },
];
