// Card data — Gauntlet AI Cohort 6, Pokémon TCG Pocket rules.
// Types: fire=Frontend, water=Data, grass=ML, electric=Infra, psychic=Agents, fighting=Evals. WEAK map in battle.js (+20).
// `name` is the card's Pokémon-style name; `real` is the person. Every card has 2 moves: its type's COMMON move (shared) + a signature move `sig`.
// Move cost: { t: n, c: m } = n energy of the card's own type + m of any type. flip: tails does nothing. self: recoil.
// ex cards are worth 2 points when knocked out. retreat = energy discarded to retreat (default 1).
window.TYPES = {
  fire: { label: "Frontend", icon: "🔥" }, water: { label: "Data", icon: "💧" }, grass: { label: "ML", icon: "🌿" },
  electric: { label: "Infra", icon: "⚡" }, psychic: { label: "Agents", icon: "🔮" }, fighting: { label: "Evals", icon: "🥊" },
  normal: { label: "Staff", icon: "⭐" }, // colorless: staff cards fill any deck up to 12 people; costs are any-energy only
};
window.COMMON = {
  fire: { name: "Hot Reload", cost: { t: 1 }, dmg: 20 },
  water: { name: "dbt Run", cost: { t: 1 }, dmg: 20 },
  grass: { name: "Fine-tune", cost: { t: 1 }, dmg: 20 },
  electric: { name: "Redeploy", cost: { t: 1 }, dmg: 20 },
  psychic: { name: "Tool Call", cost: { t: 1 }, dmg: 20 },
  fighting: { name: "Rubric Check", cost: { t: 1 }, dmg: 20 },
  normal: { name: "Standup", cost: { c: 1 }, dmg: 20 },
};
// Order matches the portal's Guess Who board (left→right, top→bottom), then the three not on the board.
window.CARDS = [
  { id: "emily-liang", name: "Swiftmily", real: "Emily Liang", photo: "photos/emily-liang.jpg", type: "fire", hp: 90,
    sig: { name: "App Store Review", cost: { t: 2 }, dmg: 70, flip: true, text: "Rejected. Resubmit." },
    flavor: "Ships iOS at Realtor.com. Has opinions about your storyboard." },
  { id: "matt-duque", name: "Duquetron", real: "Matt Duque", photo: "photos/matt-duque.jpg", type: "electric", hp: 110, retreat: 2,
    sig: { name: "HVAC Overclock", cost: { t: 2 }, dmg: 60 },
    flavor: "Ten years at Daikin. Keeps the servers and the room cool." },
  { id: "adam-roch", name: "Rochmander", real: "Adam Roch", photo: "photos/adam-roch.jpg", type: "electric", hp: 100,
    sig: { name: "Oracle Query", cost: { t: 1, c: 1 }, dmg: 50, text: "Has seen prod at 3am." },
    flavor: "Bank prod support. Nothing you deploy will surprise him." },
  { id: "jordan-phillips", name: "Jordeon", real: "Jordan Phillips", photo: "photos/jordan-phillips.jpg", type: "psychic", hp: 90,
    sig: { name: "Telehealth Launch", cost: { t: 2 }, dmg: 70, flip: true, text: "Shipped during COVID." },
    flavor: "Bootstrapped athenahealth's Telehealth. Speaks fluent MCP." },
  { id: "kevin-reynolds", name: "Kevalu", real: "Kevin Reynolds", photo: "photos/kevin-reynolds.jpg", type: "fighting", hp: 90,
    sig: { name: "Grade the Agent", cost: { t: 2 }, dmg: 70, flip: true, text: "Your PR: 3/10." },
    flavor: "Evaluates AI coding agents for a living. Yes, including this one." },
  { id: "matt-mccaleb", name: "Calebra", real: "Matt McCaleb", photo: "photos/matt-mccaleb.jpg", type: "water", hp: 100,
    sig: { name: "Acquisition", cost: { t: 2 }, dmg: 70, flip: true, text: "Now owned by UTA." },
    flavor: "Ran a data team straight through an acquisition." },
  { id: "kelly-he", name: "Kellix", real: "Kelly He", photo: "photos/kelly-he.jpg", type: "fire", hp: 90,
    sig: { name: "Fortune 100 Launch", cost: { t: 2 }, dmg: 60 },
    flavor: "E-commerce for tens of millions of users. Then an iOS app, for fun." },
  { id: "will-parks", name: "Willsaur", real: "Will Parks", photo: "photos/will-parks.jpg", type: "fire", hp: 100,
    sig: { name: "HIPAA Compliance", cost: { t: 1, c: 1 }, dmg: 50, text: "Damage is redacted." },
    flavor: "Medical hardware apps. His code is why the device works." },
  { id: "tigran-asriyan", name: "Tigrash", real: "Tigran Asriyan", photo: "photos/tigran-asriyan.jpg", type: "fire", hp: 80, retreat: 0,
    sig: { name: "IPFS Migration", cost: { t: 2, c: 1 }, dmg: 80, flip: true, text: "8s → under 1s." },
    flavor: "20k monthly users on a Solana payments app. Fast is a personality." },
  { id: "david-dean", name: "Deanzard", real: "David Dean", photo: "photos/david-dean.jpg", type: "fire", hp: 90,
    sig: { name: "Enterprise Standards", cost: { t: 1, c: 1 }, dmg: 50 },
    flavor: "Ex-AmEx UI lead. Now teaches justice-involved students to ship." },
  { id: "shamilah-faria", name: "Shamilax", real: "Shamilah Faria", photo: "photos/shamilah-faria.jpg", type: "electric", hp: 90,
    sig: { name: "Event Storm", cost: { t: 2, c: 1 }, dmg: 80, flip: true, text: "Replays every message at once." },
    flavor: "Event-driven architecture. Event-driven sleep schedule. Built this game." },
  { id: "rodolfo-rodriguez", name: "Rodolform", real: "Rodolfo Rodriguez", photo: "photos/rodolfo-rodriguez.jpg", type: "electric", hp: 100,
    sig: { name: "Cut Cloud Costs 100x", cost: { t: 2 }, dmg: 60, text: "Literally one click." },
    flavor: "Saved Broadcom 100 hours a month with one click." },
  { id: "cam-moore", name: "Camtron", real: "Cam Moore", photo: "photos/cam-moore.jpg", type: "water", hp: 100,
    sig: { name: "Snowflake Bill", cost: { t: 2 }, dmg: 70, flip: true, text: "Ouch." },
    flavor: "Founding data team at Replicated. Knows exactly what the dashboard costs." },
  { id: "john-martin", name: "Martinix", real: "John Martin", photo: "photos/john-martin.jpg", type: "electric", hp: 100,
    sig: { name: "Redis Auth Engine", cost: { t: 2 }, dmg: 60, text: "Replaced the legacy reset." },
    flavor: "Software Engineer II at Teladoc Health. Migrated Livongo members over Kafka without dropping a login." },
  { id: "josie-machalek", name: "Josieon", real: "Josie Machalek", photo: "photos/josie-machalek.jpg", type: "grass", hp: 100,
    sig: { name: "Reasoning Pipeline", cost: { t: 2 }, dmg: 70, flip: true },
    flavor: "Deloitte AI lead. Saved $700K/yr as an intern. An intern." },
  { id: "gabe-trinidad", name: "Trinidactyl", real: "Gabe Trinidad", photo: "photos/gabe-trinidad.jpg", type: "fire", hp: 90,
    sig: { name: "GraphQL Migration", cost: { t: 2 }, dmg: 60, text: "Load time 3s → 1s." },
    flavor: "Cut query load 75% at Apploi. Your components are not consistent enough." },
  { id: "sohail-siddiqui", name: "Sohailstorm", real: "Sohail Siddiqui", photo: "photos/sohail-siddiqui.jpg", type: "grass", hp: 130, ex: true, retreat: 2,
    sig: { name: "RAG Eval", cost: { t: 2, c: 1 }, dmg: 90, flip: true },
    flavor: "Builds RAG for the FDA inside GovCloud. No, you can't curl it." },
  { id: "alex-miller", name: "Alexecutor", real: "Alex Miller", photo: "photos/alex-miller.jpg", type: "psychic", hp: 100,
    sig: { name: "DevSecOps Audit", cost: { t: 2 }, dmg: 70, flip: true, text: "Held a Secret clearance." },
    flavor: "Lead engineer at ACT Labs: agent marketplaces, MCP discovery, a robotics platform on the side." },
  { id: "hank-holcomb", name: "Hankasaur", real: "Hank Holcomb", photo: "photos/hank-holcomb.jpg", type: "fire", hp: 140, ex: true, retreat: 2,
    sig: { name: "Nine-Year Tenure", cost: { t: 3 }, dmg: 100 },
    flavor: "CTO of Cheers since 2017. First hire. $100M+ brand. Still here." },
  { id: "aaryan-das", name: "Aaryanite", real: "Aaryan Das", photo: "photos/aaryan-das.jpg", type: "electric", hp: 90,
    sig: { name: "Payment Processing", cost: { t: 1, c: 1 }, dmg: 50 },
    flavor: "Payments at Bank of America. The phone menu was him. Sorry." },
  { id: "lauren-porr", name: "Porrbit", real: "Lauren Porr", photo: "photos/lauren-porr.jpg", type: "fighting", hp: 100,
    sig: { name: "SouthPAN Build 1", cost: { t: 2 }, dmg: 70, flip: true, text: "GPS augmentation, southern hemisphere." },
    flavor: "Deputy chief systems engineer on a GPS augmentation system. Yes, satellites." },
  { id: "ruben-lopez", name: "Rubenquake", real: "Ruben Lopez", photo: "photos/ruben-lopez.jpg", type: "water", hp: 100,
    sig: { name: "Wafer Signature", cost: { t: 1, c: 1 }, dmg: 50 },
    flavor: "Semiconductor yield at Samsung. Seismic data on four continents." },
  { id: "adam-nash", name: "Nashwing", real: "Adam Nash", photo: "photos/adam-nash.jpg", type: "psychic", hp: 90,
    sig: { name: "Local LLM Harness", cost: { t: 2 }, dmg: 70, flip: true, text: "No commercial assistants." },
    flavor: "Built his own coding harness around a local model. Finance and insurance domain veteran." },
  { id: "ryan-highfill", name: "Ryanigma", real: "Ryan Highfill", photo: "photos/ryan-highfill.jpg", type: "water", hp: 90,
    sig: { name: "Off the Record", cost: { t: 2 }, dmg: 70, flip: true },
    flavor: "No LinkedIn. No footprint. Maximum mystery." },
  { id: "cristina-guzman", name: "Guzmaestro", real: "Cristina Guzman", photo: "photos/cristina-guzman.jpg", type: "psychic", hp: 130, ex: true, retreat: 2,
    sig: { name: "Executive Decision", cost: { t: 2, c: 1 }, dmg: 90, flip: true, text: "Overrides the roadmap." },
    flavor: "CTO at Sendengo for four years. Before that, ran software development at Spectrum Effect." },
  { id: "koby-adu-bonnah", name: "Kobyte", real: "Koby Adu-Bonnah", photo: "photos/koby-adu-bonnah.jpg", type: "electric", hp: 130, ex: true, retreat: 2,
    sig: { name: "1.5 PB Processed", cost: { t: 2, c: 1 }, dmg: 90, self: 10, text: "Hits the disk too." },
    flavor: "Scaled a sender to half of Klaviyo's billion monthly emails. Half." },
  // Not on the portal board — photos from LinkedIn.
  { id: "josh-rochon", name: "Rochonix", real: "Josh Rochon", photo: "photos/josh-rochon.jpg", type: "fire", hp: 90,
    sig: { name: "Apollo Federation", cost: { t: 2 }, dmg: 70, flip: true, text: "Figma to React, GraphQL via Apollo." },
    flavor: "Senior React engineer at Starbucks, by way of Microsoft and BECU." },
  { id: "james-merithew", name: "Merithue", real: "James Merithew", photo: "photos/james-merithew.jpg", type: "water", hp: 100,
    sig: { name: "Executive Dashboard", cost: { t: 2 }, dmg: 60 },
    flavor: "Data viz at LG Ad Solutions. Measured the ROI of DoorDash's NBA sponsorships." },
  { id: "troy-satchell", name: "Troyager", real: "Troy Satchell", photo: "photos/troy-satchell.jpg", type: "fire", hp: 90,
    sig: { name: "Icon Subset", cost: { t: 1, c: 1 }, dmg: 50, text: "90% smaller payload." },
    flavor: "Solo founder of Clavira. Shrank a design system's icon fonts by 90% and shipped it to 7 teams." },
  // Gauntlet staff as colorless cards (deck filler). Names are Pokémon-style; no invented biographies.
  { id: "jevic", name: "Jevichu", real: "Jevic (staff)", photo: "photos/staff-jevic.jpg", type: "normal", hp: 90,
    sig: { name: "Cohort Announcement", cost: { c: 2 }, dmg: 50 }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "aaron", name: "Aaronaut", real: "Aaron (staff)", photo: "photos/staff-aaron.jpg", type: "normal", hp: 90,
    sig: { name: "Pair Programming", cost: { c: 2 }, dmg: 50 }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "sara", name: "Sarasaur", real: "Sara (staff)", photo: "photos/staff-sara.jpg", type: "normal", hp: 100,
    sig: { name: "Feedback Loop", cost: { c: 2 }, dmg: 40, text: "Heals 20 from itself." , heal: 20 }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "brett", name: "Brettle", real: "Brett (staff)", photo: "photos/staff-brett.jpg", type: "normal", hp: 90,
    sig: { name: "Deadline Extension", cost: { c: 3 }, dmg: 70, flip: true }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "arial", name: "Arialune", real: "Arial (staff)", photo: "photos/staff-arial.jpg", type: "normal", hp: 90,
    sig: { name: "Slack Reminder", cost: { c: 2 }, dmg: 50 }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "rebecca", name: "Rebechu", real: "Rebecca (staff)", photo: "photos/staff-rebecca.jpg", type: "normal", hp: 90,
    sig: { name: "Interview Prep", cost: { c: 2 }, dmg: 50 }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "derek", name: "Derekrow", real: "Derek (staff)", photo: "photos/staff-derek.jpg", type: "normal", hp: 100,
    sig: { name: "Code Review", cost: { c: 3 }, dmg: 70, flip: true }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "drew", name: "Drewgon", real: "Drew (staff)", photo: "photos/staff-drew.jpg", type: "normal", hp: 90,
    sig: { name: "Roll Call", cost: { c: 2 }, dmg: 50 }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "johnny-walker", name: "Walkarus", real: "Johnny Walker (staff)", photo: "photos/staff-johnny-walker.jpg", type: "normal", hp: 100,
    sig: { name: "Always Here", cost: { c: 3 }, dmg: 70, flip: true }, flavor: "Gauntlet staff. Fits in any deck." },
  { id: "andria", name: "Andriaz", real: "Andria (staff)", photo: "photos/staff-andria.jpg", type: "normal", hp: 90,
    sig: { name: "Attendance Check", cost: { c: 2 }, dmg: 50 }, flavor: "Gauntlet staff. Fits in any deck." },
];
// Trainer cards. Items: any number per turn. Supporters: one per turn. `effect` is interpreted in index.html.
// Staff supporters carry a photo; the five unnamed people on the STAFF board are deliberately left out. Other staff are colorless cards above.
window.TRAINERS = [
  { id: "coffee", kind: "item", name: "Coffee", effect: "heal20", text: "Heal 20 damage from your active card." },
  { id: "slack-ping", kind: "item", name: "Slack Ping", effect: "ball", text: "Put a random person from your deck into your hand." },
  { id: "hotfix", kind: "item", name: "Hotfix", effect: "hotfix", text: "This turn, your active card's retreat cost is 1 less." },
  { id: "weekly-writeup", kind: "supporter", name: "Weekly Writeup", effect: "draw2", text: "Draw 2 cards." },
  { id: "demo-day", kind: "supporter", name: "Demo Day", effect: "plus10", text: "This turn, your attacks do +10 damage." },
  { id: "hiring-partner-intro", kind: "supporter", name: "Hiring Partner Intro", effect: "sabrina", text: "Your opponent switches their active card with a benched one." },
  { id: "office-hours", kind: "supporter", name: "Office Hours", effect: "heal50", text: "Heal 50 damage from your active card." },
  { id: "stipend", kind: "supporter", name: "Stipend", effect: "energy", text: "Attach 1 energy of your type to your active card." },
  // Gauntlet staff
  { id: "austen", kind: "supporter", staff: true, name: "Austen", photo: "photos/staff-austen.jpg", effect: "draw3", text: "Draw 3 cards." },
  { id: "ash", kind: "supporter", staff: true, name: "Ash", photo: "photos/staff-ash.jpg", effect: "plus10", text: "This turn, your attacks do +10 damage. Gotta be the very best." },
  { id: "zac", kind: "supporter", staff: true, name: "Zac", photo: "photos/staff-zac.jpg", effect: "redcard", text: "Your opponent shuffles their hand into their deck and draws 3." },
  { id: "byron", kind: "supporter", staff: true, name: "Byron", photo: "photos/staff-byron.jpg", effect: "shield", text: "During your opponent's next turn, your active card takes 20 less damage." },
  { id: "holdy", kind: "supporter", staff: true, name: "Holdy", photo: "photos/staff-holdy.jpg", effect: "flipEnergy", text: "Flip a coin until tails. For each heads, attach 1 energy of your type to your active card." },
  { id: "tom", kind: "supporter", staff: true, name: "Tom", photo: "photos/staff-tom.jpg", effect: "heal50", text: "Heal 50 damage from your active card." },
  { id: "tom-2", kind: "supporter", staff: true, name: "Tom", photo: "photos/staff-tom-2.jpg", effect: "moveEnergy", text: "Move 1 energy from each of your benched cards to your active card." },
  { id: "matthew-poole", kind: "supporter", staff: true, name: "Matthew Poole", photo: "photos/staff-matthew-poole.jpg", effect: "sabrina", text: "Hiring partner intro: your opponent switches their active card with a benched one." },
  { id: "jon-lucas", kind: "supporter", staff: true, name: "Jon Lucas", photo: "photos/staff-jon-lucas.jpg", effect: "retreatFree", text: "Demo Day walk-on: this turn, your active card's retreat cost is 0." },
];
