// Maps are 25 cols x 15 rows of 32px tiles. Short rows are space-padded.
// Legend:  = solid   ~ hallucination (vanishes on touch)   ^ spikes   @ spawn
//          E exit    X fake exit (kills)   F flaky-flag spawn point
//          ! "ignore previous instructions" sign (inverts controls 3s)
//          1-9 helpful signs, text from `signs`
// Per-level trap flags: rateLimit:true, vignette:<seconds>, flaky:<probability>
const LEVELS = [
  {
    name: "Hallucination",
    map: [
      "                         ",
      "                         ",
      "               X         ",
      "             =====       ",
      "                         ",
      "        ~~~              ",
      "                ===      ",
      "   @      ===            ",
      "  ====                   ",
      "                     ~~  ",
      "                        E",
      "                       ==",
      "                         ",
      "     ===       ====      ",
      "^^^^^^^^^^^^^^^^^^^^^^^^^",
    ],
  },
  {
    name: "Prompt Injection",
    signs: { 1: "-> jump here", 2: "safe!" },
    map: [
      "                         ",
      "                         ",
      "                         ",
      "                         ",
      "                         ",
      "                         ",
      "                         ",
      "             2           ",
      "           ~~~~~         ",
      "       ==                ",
      "     1          !    E   ",
      " @  ==      ==  =  ======",
      "===^^^^^^^^^^^^^^^^^^^^^^",
      "                         ",
      "                         ",
    ],
  },
  {
    name: "Rate Limited",
    rateLimit: true,
    map: [
      "                         ",
      "                         ",
      "                         ",
      "                         ",
      "E                        ",
      "===  ===  ===  ===  ===  ",
      "                         ",
      "                         ",
      "                        =",
      "@                        ",
      "===  ===  ===  ===  ===  ",
      "                         ",
      "                         ",
      "^^^^^^^^^^^^^^^^^^^^^^^^^",
      "                         ",
    ],
  },
  {
    name: "Context Window",
    vignette: 12,
    map: [
      "                         ",
      "     ^      ^  ^      E  ",
      "  ===== ======== ========",
      "                         ",
      "=                        ",
      "                         ",
      "   ^       ^   ^         ",
      "  =====  ======= =====   ",
      "                         ",
      "                       = ",
      "                         ",
      "@    ^   ^   ^     ^     ",
      "======  ======= =========",
      "                         ",
      "^^^^^^^^^^^^^^^^^^^^^^^^^",
    ],
  },
  {
    name: "Flaky Eval",
    flaky: 0.3,
    map: [
      "                         ",
      "                         ",
      "                         ",
      "  F                  F   ",
      " ====   ~~~        ===== ",
      "      =         =        ",
      "           F             ",
      "         =====           ",
      "                         ",
      "@                       E",
      "====   =====   ====  ====",
      "                         ",
      "                         ",
      "^^^^^^^^^^^^^^^^^^^^^^^^^",
      "                         ",
    ],
  },
];
